name: Deploy to lower environment (dev etc)

permissions: {}

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev
  push:
    branches: master

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  check-env:
    name: Fail if production environment
    if: ${{ inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Failing intentionally. Please use the 'Deploy to production' workflow."
          exit 1
  call-workflow:
    if: ${{ inputs.environment != 'prod' }}
    permissions:
      id-token: write # Needed to access ECR and ECS
      contents: read # Needed to access commit details and other repository info
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@c76e5ccd9556fbea52bc41548f7ceed5985ad775 # v5.1.0
    with:
      app-name: concentrate
      environment: ${{ github.event.inputs.environment || 'dev' }}
      docker-additional-tags: ${{ github.event.inputs.environment || 'dev' }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
